### PR TITLE
Improve `.npmignore` to exclude eg. `.nyc_output`

### PR DESCRIPTION
**Pull request by voxpelli**
This reverts the `.npmignore` to ignore everything except for the very files that needs to be included. Thus fixes the fact that eg. `.nyc_output` gets published to npm.

Reason why `.nyc_output` is currently published to npm is that `.npmignore` _replaces_ `.gitignore`, rather than extends it.

Edit: Here's a link to the Renovate diff where I found out that this was happening: https://app.renovatebot.com/package-diff?name=eslint-plugin-chai-friendly&from=0.6.0&to=0.7.2

### CODE REVIEW

**Comment by ihordiachenko** [comment]
Hi @voxpelli. I think it would be cleaner to use ["files"](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) field in `package.json` to explicitly whitelist the source files

**Comment by voxpelli** [comment]
I agree @ihordiachenko, then if you publish using eg `np`, then it can check with you whether it’s correct or not that a bee files is included or excluded 👍

Should I change this PR to files?

**Comment by ihordiachenko** [comment]
@voxpelli yes, update the PR and I'll merge it

**Comment by voxpelli** [comment]
@ihordiachenko 3.5 years later and I have now done so, sorry for delay 🙈

**Comment by ihordiachenko** [comment]
@voxpelli be like:
image

Lgtm. Will include in the next release

**Pull request merged**
